version: '3'

services:
  db:
    build: ./db
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    ports:
      - 1433:1433
  api:
    build: ./ProductsAPI
    environment: 
      - DATABASE=mssql
    ports:
      - 44365:44365
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - 4200:80
    depends_on:
      - api
