version: '3'

services:
  db:
    build: ./db
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    ports:
      - 1433:1433
  back:
    build: ./back
    ports:
      - 5000:80
    depends_on:
      - db
  front:
    build: ./front
    ports:
      - 8888:80
    depends_on:
      - back
