POST https://localhost:44365/api/Login/authenticate
Content-Type: application/json

{
  "username": "manager",
  "password": "manager"
}

###
GET https://localhost:44365/api/Categories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmFnZXIiLCJyb2xlIjoibWFuYWdlciIsIm5iZiI6MTYyNjc5NDQ1MCwiZXhwIjoxNjI2Nzk0NTEwLCJpYXQiOjE2MjY3OTQ0NTB9.duBZW66aSYWTJ5TjezXK3zanGlnSvalf62SoasK4Psg
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmFnZXIiLCJyb2xlIjoibWFuYWdlciIsIm5iZiI6MTYyNjc5MjkwMCwiZXhwIjoxNjI2ODc5MzAwLCJpYXQiOjE2MjY3OTI5MDB9.TSXJd1IiJW0fvve44UWLVXgdWLhXOn9m4b6NkRdNjWo
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNjI2NzkyODc1LCJleHAiOjE2MjY4NzkyNzUsImlhdCI6MTYyNjc5Mjg3NX0.9F0lieWOGB6xSAtRozUEgG8oSfcu2REQn1-LefKKXXk
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImN1c3RvbWVyIiwicm9sZSI6ImN1c3RvbWVyIiwibmJmIjoxNjI2NzkzMDI4LCJleHAiOjE2MjY4Nzk0MjgsImlhdCI6MTYyNjc5MzAyOH0.b0dod8Y-RjPs6zVmd6l_DsQ9G9jUEY9BJwdeQFzw6cE

###
GET https://localhost:44365/api/Categories
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6Im1hbmFnZXIiLCJyb2xlIjoibWFuYWdlciIsIm5iZiI6MTYyNjc5MjkwMCwiZXhwIjoxNjI2ODc5MzAwLCJpYXQiOjE2MjY3OTI5MDB9.TSXJd1IiJW0fvve44UWLVXgdWLhXOn9m4b6NkRdNjWo
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNjI2NzkyODc1LCJleHAiOjE2MjY4NzkyNzUsImlhdCI6MTYyNjc5Mjg3NX0.9F0lieWOGB6xSAtRozUEgG8oSfcu2REQn1-LefKKXXk
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImN1c3RvbWVyIiwicm9sZSI6ImN1c3RvbWVyIiwibmJmIjoxNjI2NzkzMDI4LCJleHAiOjE2MjY4Nzk0MjgsImlhdCI6MTYyNjc5MzAyOH0.b0dod8Y-RjPs6zVmd6l_DsQ9G9jUEY9BJwdeQFzw6cE